# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fPZLT24GhzRHmSQoj9F1dduEcwaIErzv
"""

import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

x = np.array([-7.0, -4.0, -1.0, 2.0, 5.0, 8.0, 11.0, 14.0])
y = np.array([3.0, 6.0, 9.0, 12.0, 15.0, 18.0, 21.0, 24.0])

# visualisera min data
plt.scatter(x, y)

"""Bygga en modell som förutspår datan utifrån olika värden, t.ex  17, 20, 27 etc.


"""

x.ndim

"""STEG FÖR ATT BYGGA EN MODELL i tensorflow



1.   Create
2.   Compile
3.   Fit






"""

# Set seed
tf.random.set_seed(42)

# STEP1.  Create.

model = tf.keras.Sequential([tf.keras.layers.Dense(1)])  # output Layer

# Step2.  Compile

model.compile(
    loss=tf.keras.losses.mae,
    optimizer=tf.keras.optimizers.SGD(),  # hur modellen förbättras
    metrics=["mae"],
)

# Step3.  Fit
model.fit(
    tf.expand_dims(x, axis=-1), y, epochs=50
)  # Kollar på mönster när jag kör modellen 5 gånger.

x, y

y_pred = model.predict(np.array([49]))
y_pred

"""IMPROVE MODEL
CREATE


1.   More layers
2.   More hidden units
3.   Change Activation function

COMPILE
1.   Optimization function
2.   Learning rate

FITTING
1.   More trials (EPOCHS)

"""


"""LÖSNINGSFÖRSLAG på indata: 30,  förväntat: 40

model1:  52.3,  23.1,  23.6,  51.55,   51.09

model2:  40.45,  37.8s, 39.4, 40.94,  39.03

MIN MODELL2
"""

x, y

# Set random seed
tf.random.set_seed(42)

# Step1 Create model with Sequential API

# Set seed
tf.random.set_seed(42)

# STEP1.  Create.

model2 = tf.keras.Sequential(
    [
        tf.keras.layers.Dense(50, activation=None),
        tf.keras.layers.Dense(1),  # output Layer
    ]
)

# Step2.  Compile

model2.compile(
    loss=tf.keras.losses.mae,
    optimizer=tf.keras.optimizers.Adam(0.01),  # hur modellen förbättras
    metrics=["mae"],
)

# Step3.  Fit
model2.fit(
    tf.expand_dims(x, axis=-1), y, epochs=100
)  # Kollar på mönster när jag kör modellen 5 gånger.

y_pred = model2.predict(np.array([49]))
y_pred
